spring:
  kafka:
    bootstrap-servers:
      - 10.121.1.106:9092
      - 10.121.1.107:9092
      - 10.121.1.108:9092
    # 消息消费监听器
    listener:
      type: BATCH
      concurrency: 3
      poll-timeout: 1500
    # 消费者
    consumer:
      group-id: consumer-demo
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 50
      fetch-max-wait: 500
      fetch-min-size: 102400
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 授权
      security:
        protocol: SASL_PLAINTEXT
      properties:
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaroot" password="pfBkP4wqtf3VkvYsH2Cyzy5BkX36CBeVrmbYraSanA==B";
    # 生产者
    producer:
      retries: 3
      batch-size: 4096
      buffer-memory: 4096000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 授权
      security:
        protocol: SASL_PLAINTEXT
      properties:
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaroot" password="pfBkP4wqtf3VkvYsH2Cyzy5BkX36CBeVrmbYraSanA==B";

kafka:
  topic: event-current-data
  partition: 1